version: 2.1

references:
  workspace_root: &workspace_root ~/web
  yarn_cache_config: &yarn_cache_config
    key: dependencies-{{ .Branch }}-{{ checksum "yarn.lock" }}-{{ checksum "package.json" }}
    paths:
      - .

  yarn_restore_cache: &yarn_restore_cache
    restore_cache:
      <<: *yarn_cache_config
      name: Restore yarn cache

  yarn_save_cache: &yarn_save_cache
    save_cache:
      <<: *yarn_cache_config
      name: Save yarn cache

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

  system_info: &system_info
    run:
      name: System infomation
      command: |
        echo "Node $(node -v)"
        echo "Yarn v$(yarn --version)"
  deps: &deps
    run:
      name: Install dependencies
      command: yarn --pure-lockfile

  docker_image_for_ci: &docker_image_for_ci
    docker:
      - image: node:10.15.0
        environment:
          TZ: "/usr/share/zoneinfo/Asia/Tokyo"
          REVIEWDOG_VERSION: "0.9.11"

  docker_image_for_deploy: &docker_image_for_deploy
    docker:
      - image: makki0205/deploy

executors:
  node_stage:
    <<: *docker_image_for_ci
    working_directory: *workspace_root

  deploy_stage:
    <<: *docker_image_for_deploy
    working_directory: *workspace_root

jobs:
  setup:
    executor: node_stage
    steps:
      - checkout
      - *system_info
      - *deps
      - *yarn_save_cache
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - node_modules

  run_lint:
    executor: node_stage
    steps:
      - checkout
      - *attach_workspace
      - run:
          name: yarn lint
          command: yarn lint

  run_test:
    executor: node_stage
    steps:
      - checkout
      - *attach_workspace
      - run:
          name: Unit test
          command: yarn test

  run_build:
    executor: node_stage
    steps:
      - checkout
      - *attach_workspace
      - run:
          name: export release version file
          command: sh scripts/release.sh
      - run:
          name: staging build
          command: yarn build
          environment:
            NODE_ENV: staging
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - .

  run_build_prod:
    executor: node_stage
    steps:
      - checkout
      - *attach_workspace
      - run:
          name: production build
          command: yarn build:prod
          environment:
            NODE_ENV: production
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - .

  production:
    executor: deploy_stage
    steps:
      - checkout
      - attach_workspace:
          at: *workspace_root
      - run:
          name: aws login
          command: make -f .circleci/ci.mk login
      - run:
          name: deploy
          command: make -f .circleci/ci.mk deploy

workflows:
  build_and_deploy:
    jobs:
      - setup
      - run_lint:
          requires:
            - setup
      - run_test:
          requires:
            - setup
      - run_build:
          requires:
            - setup
          filters:
            branches:
              ignore: master
      - run_build_prod:
          requires:
            - setup
          filters:
            branches:
              only: master
      - production:
          requires:
            - setup
            - run_lint
            - run_test
            - run_build_prod
          filters:
            branches:
              only: master